language: php

php:
  - '7.2'
  - '7.1'
  - '7.0'

before_script:
 - printf "\n" | pecl install imagick
 - php -m
 - composer install

before_install:
 - composer self-update

script:
 - composer test
