version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: tronald-web
    depends_on:
      php:
        condition: service_started
    networks:
      - tronald-network
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    container_name: tronald-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/tronald
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_started
    networks:
      - tronald-network

  postgres:
    image: tronalddump/postgres
    container_name: tronald-db
    ports:
      - "5432:5432"
    networks:
      - tronald-network

networks:
  tronald-network:
    driver: bridge
