version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: tronald-web
    depends_on:
      php:
        condition: service_started
    networks:
      - tronald-network
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    container_name: tronald-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_started
    networks:
      - tronald-network

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
        - BACKUP_URI=s3://io.tronalddump.api/database/latest.sql
    container_name: tronald-db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    ports:
      - "5432:5432"
    networks:
      - tronald-network
    volumes:
      - ./docker/postgres/data:/docker-entrypoint-initdb.d/

networks:
  tronald-network:
    driver: bridge
