version: '3'

services:
  postgres:
    image: tronalddump/postgres
    container_name: tronalddump-db
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
