# -------------------------------------------------------------------------------------------------
# API ROUTES
# -------------------------------------------------------------------------------------------------

api.index :
    path     : /
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\IndexController::getAction

api.integration_slack :
    path     : /integration/slack
    methods  : POST
    defaults :
        _controller : \Tronald\App\Api\Controller\SlackController::postAction
    options  :
        _before_middlewares : \Tronald\App\Api\Middleware\Verification::slackOrigin

api.get_quote :
    path     : /quote/{id}
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\QuoteController::getAction

api.get_random_quote :
    path     : /random/quote
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\RandomQuoteController::getAction

api.get_random_meme :
    path     : /random/meme
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\RandomMemeController::getAction

api.search_quote :
    path     : /search/quote
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\SearchQuoteController::getAction

api.system_time :
    path     : /system/time
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\SystemTimeController::getAction

api.tags :
    path     : /tag
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\TagsController::getAction

api.get_tag  :
    path     : /tag/{tag}
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\TagsController::getTagAction

api.teapot :
    path     : /teapot
    methods  : GET
    defaults :
        _controller : \Tronald\App\Api\Controller\TeapotController::getAction
